import { Product } from '../models/product';

export const products: Product[] = [
  {
    id: 'product123',
    title: 'Maroon Polo',
    price: 499.99,
    category: 'men',
    imageUrl: 'https://via.placeholder.com/300x200?text=Polo',
  },
  {
    id: 'product234',
    title: 'White T-shirt',
    price: 999.99,
    category: 'men',
    imageUrl: 'https://via.placeholder.com/300x200?text=Tshirt',
  },
  {
    id: 'product345',
    title: 'Blue Jeans',
    price: 79.99,
    category: 'men',
    imageUrl: 'https://via.placeholder.com/300x200?text=Jeans',
  },
  {
    id: 'product456',
    title: 'Running Shoes',
    price: 89.99,
    category: 'men',
    imageUrl: 'https://via.placeholder.com/300x200?text=Shirt',
  },
  {
    id: 'product567',
    title: 'Jacket',
    price: 49.99,
    category: 'men',
    imageUrl: 'https://via.placeholder.com/300x200?text=Jacket',
  },
  {
    id: 'product678',
    title: 'Hoodie',
    price: 199.99,
    category: 'men',
    imageUrl: 'https://via.placeholder.com/300x200?text=hoodie',
  },
  {
    id: 'product456',
    title: 'Sneakers',
    price: 89.99,
    category: 'men',
    imageUrl: 'https://via.placeholder.com/300x200?text=Sneakers',
  },
  {
    id: 'product678',
    title: 'Watch',
    price: 199.99,
    category: 'men',
    imageUrl: 'https://via.placeholder.com/300x200?text=Watch',
  },
  //women
  {
    id: 'product678',
    title: 'Watch',
    price: 199.99,
    category: 'women',
    imageUrl: 'https://via.placeholder.com/300x200?text=Watch',
  },
  {
    id: 'product678',
    title: 'Jeans',
    price: 199.99,
    category: 'women',
    imageUrl: 'https://via.placeholder.com/300x200?text=Jeans',
  },
  {
    id: 'product678',
    title: 'Shopping Bag',
    price: 199.99,
    category: 'women',
    imageUrl: 'https://via.placeholder.com/300x200?text=bag',
  },
  {
    id: 'product678',
    title: 'Kurta',
    price: 199.99,
    category: 'women',
    imageUrl: 'https://via.placeholder.com/300x200?text=Kurta',
  },
  //kids
  {
    id: 'product678',
    title: 'Kurta',
    price: 199.99,
    category: 'kids',
    imageUrl: 'https://via.placeholder.com/300x200?text=Kurta',
  },
  {
    id: 'product678',
    title: 'Shirt',
    price: 199.99,
    category: 'kids',
    imageUrl: 'https://via.placeholder.com/300x200?text=Shirt',
  },
  //Summer sale
  {
    id: 'product678',
    title: 'Kurta',
    price: 199.99,
    category: 'summer-sale',
    imageUrl: 'https://via.placeholder.com/300x200?text=Kurta',
  },
  {
    id: 'product678',
    title: 'Shirt',
    price: 199.99,
    category: 'summer-sale',
    imageUrl: 'https://via.placeholder.com/300x200?text=Shirt',
  },
  {
    id: 'product123',
    title: 'Maroon Polo',
    price: 499.99,
    category: 'summer-sale',
    imageUrl: 'https://via.placeholder.com/300x200?text=Polo',
  },
  {
    id: 'product234',
    title: 'White T-shirt',
    price: 999.99,
    category: 'summer-sale',
    imageUrl: 'https://via.placeholder.com/300x200?text=Tshirt',
  },
  {
    id: 'product345',
    title: 'Blue Jeans',
    price: 79.99,
    category: 'summer-sale',
    imageUrl: 'https://via.placeholder.com/300x200?text=Jeans',
  },
  {
    id: 'product456',
    title: 'Running Shoes',
    price: 89.99,
    category: 'summer-sale',
    imageUrl: 'https://via.placeholder.com/300x200?text=Shirt',
  },
  {
    id: 'product567',
    title: 'Jacket',
    price: 49.99,
    category: 'summer-sale',
    imageUrl: 'https://via.placeholder.com/300x200?text=Jacket',
  },
  {
    id: 'product678',
    title: 'Hoodie',
    price: 199.99,
    category: 'summer-sale',
    imageUrl: 'https://via.placeholder.com/300x200?text=hoodie',
  },
  {
    id: 'product456',
    title: 'Sneakers',
    price: 89.99,
    category: 'summer-sale',
    imageUrl: 'https://via.placeholder.com/300x200?text=Sneakers',
  },
  {
    id: 'product678',
    title: 'Watch',
    price: 199.99,
    category: 'summer-sale',
    imageUrl: 'https://via.placeholder.com/300x200?text=Watch',
  },
  {
    id: 'product678',
    title: 'Jeans',
    price: 199.99,
    category: 'summer-sale',
    imageUrl: 'https://via.placeholder.com/300x200?text=Jeans',
  },
  {
    id: 'product678',
    title: 'Shopping Bag',
    price: 199.99,
    category: 'summer-sale',
    imageUrl: 'https://via.placeholder.com/300x200?text=bag',
  },
];
